# Generated by Django 5.1.4 on 2025-02-02 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('photo', models.ImageField(default='default.png', upload_to='camera_reference_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('default_value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('bool', 'Boolean'), ('float', 'Float')], default='str', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CameraContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('last_started', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='management.camera')),
            ],
            options={
                'db_table': 'camera_containers',
            },
        ),
    ]
