# Generated by Django 5.1.4 on 2024-12-28 11:07

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_setting_key_setting_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', pgvector.django.vector.VectorField(dimensions=10)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='management.camera')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='management.zone')),
            ],
        ),
        migrations.DeleteModel(
            name='CalibrationPoint',
        ),
    ]
