# Generated by Django 5.1.4 on 2024-12-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_zone_boundary_delete_calibrationpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
