# Generated by Django 5.1.4 on 2024-12-28 16:31

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_zone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='polygon',
            field=pgvector.django.vector.VectorField(dimensions=20),
        ),
    ]
