# Generated by Django 5.1.4 on 2025-01-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_boundary_polygon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundary',
            options={'verbose_name_plural': 'Boundaries'},
        ),
        migrations.CreateModel(
            name='CameraContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('last_started', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='management.camera')),
            ],
            options={
                'db_table': 'camera_containers',
            },
        ),
    ]
