# Generated by Django 5.1.4 on 2025-01-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_boundary_options_cameracontainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='transformation_matrix',
        ),
    ]
