# Generated by Django 5.1.4 on 2025-01-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_camera_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='camera_reference_photos/'),
        ),
    ]
