# Generated by Django 5.1.4 on 2025-01-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_camera_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='default_value',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
