# Generated by Django 5.1.4 on 2025-02-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_setting_default_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingsubject',
            name='user',
        ),
        migrations.DeleteModel(
            name='Boundary',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.DeleteModel(
            name='TrackingSubject',
        ),
    ]
