# Generated by Django 5.1.4 on 2024-12-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='track_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
