# Generated by Django 5.1.4 on 2024-12-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_detection_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='camera_id',
            new_name='camera',
        ),
    ]
