# Generated by Django 5.1.4 on 2025-01-27 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0004_alter_recognition_user'),
        ('stats', '0004_alter_detection_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_in', to='face_recognition.recognition')),
                ('recognition_out', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries_out', to='face_recognition.recognition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
