# Generated by Django 5.1.4 on 2025-01-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0002_faceembedding_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='photo',
            field=models.ImageField(null=True, upload_to='recognition_face_photos/'),
        ),
    ]
