# Generated by Django 5.1.3 on 2024-12-02 14:38

import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 second')),
            ],
            options={
                'db_table': 'entry_data',
            },
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 second')),
            ],
            options={
                'db_table': 'exit_data',
            },
        ),
    ]
