# Generated by Django 5.1.2 on 2024-11-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_admin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.IntegerField(choices=[(0, 'Entry'), (1, 'Exit'), (2, 'Track')], default=2),
        ),
    ]
